# Generated by Django 3.2.5 on 2022-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=64, verbose_name='사용자 명')),
                ('user_email', models.EmailField(max_length=256, verbose_name='이메일')),
                ('password', models.CharField(max_length=256, verbose_name='비밀 번호')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='등록일')),
            ],
            options={
                'verbose_name': '사이트 이용자',
                'verbose_name_plural': '사이트 이용자 목록',
                'db_table': 't_user',
            },
        ),
    ]
