# Generated by Django 3.2.5 on 2022-03-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='제목')),
                ('contents', models.TextField(verbose_name='내용')),
                ('insert_date', models.DateTimeField(auto_now=True, verbose_name='작성일')),
                ('update_date', models.DateTimeField(null=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '게시판',
                'verbose_name_plural': '게시판 목록',
                'db_table': 't_board',
            },
        ),
    ]
