# Generated by Django 3.2.5 on 2022-03-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='board',
            name='update_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='수정일'),
        ),
    ]
